<?php

/**
 * Prepares variables for `breadcrumb.html.twig`.
 **/
function yourtheme_preprocess_breadcrumb(&$variables){

  // Remove 'Home' from breadcrumb trail.
  if (count($variables['breadcrumb'])) {
    array_shift($variables['breadcrumb']);
  }
}

/**
 * Implements hook_preprocess_node().
 */
function walnut_preprocess_node(&$variables) {
	// Check if the node is a Landing Page.
	if ($variables['node']->bundle() === 'landing_page') {
	// Target the header image field using its machine name.
	if (!empty($variables['content']['field_lp_header_image'])) {
	    // Add inline CSS to reset the margin.
	    $variables['content']['field_lp_header_image']['#attributes']['style'] = 'margin-inline-start: 0 !important;';
		}
	}
}
/**
 * Implements hook_preprocess_html().  This is used to hide the donate button on the donate page
 */
function walnut_preprocess_html(&$variables) {
  // Add node-specific class to body for better targeting in CSS.
  $node = \Drupal::routeMatch()->getParameter('node');
  if ($node instanceof \Drupal\node\NodeInterface) {
    $variables['attributes']['class'][] = 'page-node-' . $node->id();
  }
}
